### ISSUE TITLE
Support spaces in the project path

### ISSUE THREAD

**Issue by mordka** [OpenDroneMap/ODM#1006]
### How did you install OpenDroneMap? (Docker, natively, ...)?
docker

### What is the problem?
OpenSfM stage fails for project path that contains spaces

```

running /code/SuperBuild/src/opensfm/bin/opensfm extract_metadata /project path with spaces/code/opensfm[0m
usage: opensfm [-h] command ...
opensfm: error: unrecognized arguments: path with spaces/code/opensfm
Traceback (most recent call last):
File "/code/run.py", line 56, in <module>
app.execute()
File "/code/stages/odm_app.py", line 92, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 373, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 373, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 373, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 354, in run
self.process(self.args, outputs)
File "/code/stages/run_opensfm.py", line 25, in process
octx.extract_metadata(self.rerun())
File "/code/opendm/osfm.py", line 155, in extract_metadata
self.run('extract_metadata')
File "/code/opendm/osfm.py", line 21, in run
(context.opensfm_path, command, self.opensfm_project_path))
File "/code/opendm/system.py", line 76, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 2
```

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

ODM should handle `--project-path` that contains white characters

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Run ODM specifying `--project-path` that contains spaces

**Comment by mordka** [comment]
Same problem happens during MVE stage https://github.com/OpenDroneMap/ODM/blob/a15256943d438236ae3a72ac2848a5d5eb2b9cf2/stages/mve.py#L45
