### ISSUE TITLE
native build success but cannot run, no module named pyodm

### ISSUE THREAD

**Issue by CanCanZeng** [OpenDroneMap/ODM#1158]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions and discussion please open a topic on http://community.opendronemap.org/c/opendronemap. 

Please use the format below to report bugs and faults. It will help improve the resolution process. 
****************************************

### How did you install OpenDroneMap? (Docker, natively, ...)?

natively

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

ubuntu16.04 and Chrome 68 on Linux

### What is the problem?

After I build ODM with the code `sudo bash configure.sh install `, everything seems to be alright, but when I run `./run.sh --project-path /datasets odm_data_aukerman` , there is an error:

```
Traceback (most recent call last):
  File "~/ODM/ODM/run.py", line 4, in <module>
    from opendm import config
  File "~/ODM/ODM/opendm/config.py", line 7, in <module>
    from pyodm import Node, exceptions
ImportError: No module named pyodm
```

And I search in ODM folder, there is no file named pyodm.py or something like this.

Then I try `./test.sh` , the output is:
```
======================================================================
ERROR: test_types (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_types
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "~/ODM/tests/test_types.py", line 2, in <module>
    from opendm import types
  File "opendm/types.py", line 5, in <module>
    from opendm import location
  File "opendm/location.py", line 3, in <module>
    from pyproj import Proj, Transformer, CRS
ImportError: No module named pyproj


======================================================================
ERROR: test_gcp (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_gcp
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "~/ODM/tests/test_gcp.py", line 6, in <module>
    from opendm.gcp import GCPFile
  File "opendm/gcp.py", line 4, in <module>
    from opendm import location
  File "opendm/location.py", line 3, in <module>
    from pyproj import Proj, Transformer, CRS
ImportError: No module named pyproj


======================================================================
ERROR: test_osfm (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_osfm
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "~/ODM/tests/test_osfm.py", line 3, in <module>
    from opendm.osfm import get_submodel_argv, get_submodel_args_dict
  File "opendm/osfm.py", line 12, in <module>
    from opensfm.large import metadataset
  File "~/ODM/SuperBuild/src/opensfm/opensfm/large/metadataset.py", line 7, in <module>
    from opensfm import io
  File "~/ODM/SuperBuild/src/opensfm/opensfm/io.py", line 15, in <module>
    import pyproj
ImportError: No module named pyproj


======================================================================
ERROR: test_remote (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_remote
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "~/ODM/tests/test_remote.py", line 5, in <module>
    from opendm.remote import LocalRemoteExecutor, Task, NodeTaskLimitReachedException
  File "opendm/remote.py", line 11, in <module>
    from opendm import config
  File "opendm/config.py", line 7, in <module>
    from pyodm import Node, exceptions
ImportError: No module named pyodm


----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=4)
```

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I just run `sudo bash configure.sh install ` to compile the project, nothing else.
And I tried to checkout to branch v1.0.2, run `sudo bash configure.sh reinstall `, the output is the same.
Then I tried to run the command in configure.sh one by one in a bash, but the output is still the same.

**Comment by pierotofy** [comment]
There's probably an error while installing pyodm (`pip install pyodm`).

Note running ODM natively is not recommended. Any reason you're not using docker?

In any case, we should move this conversation over to https://community.opendronemap.org as this looks like an installation question/problem and not a bug. :pray:
