### ISSUE TITLE
ODM 2.0.0 Crashes joblib.externals.loky.process_executor.TerminatedWorkerError

### ISSUE THREAD

**Issue by katarias** [OpenDroneMap/ODM#1164]
# How did you install OpenDroneMap? (Docker, natively, ...)?

Tested with both Docker and Natively installed over Ubuntu 18.04

### What is the problem?
ODM Failed to process dataset greter than 100 images while running match_features. Server has more than enough resources 32 Cpu + 128 G Ram. Same datasets working fine with ODM 1.0.1
Tested with Multiple datasets.

Getting warning while running "Detect Features" functions - 
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.

ODM Failed while running "match_features" after few min - 

```2020-10-13 09:17:58,563 DEBUG: No segmentation for DJI_0106.JPG, no features masked.
2020-10-13 09:17:59,629 ERROR: exception calling callback for <Future at 0x7f15955dd780 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused 
by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the
 workers are {SIGKILL(-9)}
Traceback (most recent call last):
  File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/code/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 29, in run
    pairs_matches, preport = matching.match_images(data, images, images)
  File "/code/SuperBuild/src/opensfm/opensfm/matching.py", line 43, in match_images
    return match_images_with_pairs(data, exifs, ref_images, pairs), preport
  File "/code/SuperBuild/src/opensfm/opensfm/matching.py", line 67, in match_images_with_pairs
    matches = context.parallel_map(match_unwrap_args, args, processes, jobs_per_process)
  File "/code/SuperBuild/src/opensfm/opensfm/context.py", line 41, in parallel_map
    return Parallel(batch_size=batch_size)(delayed(func)(arg) for arg in args)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 510, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/reusable_executor.py", line 151, in submit
    fn, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 1022, in submit
    raise self._flags.broken

joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}
Traceback (most recent call last):
  File "/code/run.py", line 68, in <module>
    app.execute() 
  File "/code/stages/odm_app.py", line 95, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 356, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 356, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 356, in run
    self.next_stage.run(outputs)
  File "/code/opendm/types.py", line 337, in run
    self.process(self.args, outputs)
  File "/code/stages/run_opensfm.py", line 30, in process
    octx.feature_matching(self.rerun())
  File "/code/opendm/osfm.py", line 277, in feature_matching
    self.run('match_features')
  File "/code/opendm/osfm.py", line 22, in run
    (context.opensfm_path, command, self.opensfm_project_path))
  File "/code/opendm/system.py", line 79, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

It should process fine. Same dataset images working with ODM 1.0.1

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Processing with docker and Native install as well
docker run -ti --rm -v ~/dataset:/datasets opendronemap/odm --project-path /datasets project --dsm --orthophoto-resolution 2

Tested with Multiple Datasets more than 100 Images. It works well for 50 images.

**Comment by pierotofy** [comment]
> workers are {SIGKILL(-9)}

This means you're running out of memory. :pray: 

Not a bug; just allocate more memory to the docker environment (see docs.docker.com for instructions on how to do that).
