### ISSUE TITLE
Dockerfile . Lower versions of ODM such as 2.1.1 hints ModuleNotFoundError: No module named 'osr'

### ISSUE THREAD

**Issue by githubhanjunjun** [OpenDroneMap/ODM#1262]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker: FROM opendronemap/odm:2.1.1

### What is the problem?

Traceback (most recent call last):
  File "/code/run.py", line 18, in <module>
    from stages.odm_app import ODMApp
  File "/code/stages/odm_app.py", line 16, in <module>
    from stages.odm_orthophoto import ODMOrthoPhotoStage
  File "/code/stages/odm_orthophoto.py", line 13, in <module>
    from opendm import pseudogeo
  File "/code/opendm/pseudogeo.py", line 1, in <module>
    import osr
ModuleNotFoundError: No module named 'osr'

**Comment by pierotofy** [comment]
We don't support older versions, any reason you can't use the latest one?
