### ISSUE TITLE
problem on windows10

### ISSUE THREAD

**Issue by tangjj110** [OpenDroneMap/ODM#1385]
### How did you install OpenDroneMap? (Docker, natively, ...)?

ODM_Setup_2.6.7.exe

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

windows10

### What is the problem?
ODM can be installed natively on Windows,but I I have a problem when i tried it.

[INFO]    Initializing ODM - Sun Dec 19 23:54:17  2021
[INFO]    ==============
[INFO]    auto_boundary: False
[INFO]    boundary: {}
[INFO]    build_overviews: False
[INFO]    camera_lens: auto
[INFO]    cameras: {}
[INFO]    cog: False
[INFO]    copy_to: None
[INFO]    crop: 3
[INFO]    debug: False
[INFO]    dem_decimation: 1
[INFO]    dem_euclidean_map: False
[INFO]    dem_gapfill_steps: 3
[INFO]    dem_resolution: 5
[INFO]    depthmap_resolution: 640
[INFO]    dsm: False
[INFO]    dtm: False
[INFO]    end_with: odm_postprocess
[INFO]    fast_orthophoto: False
[INFO]    feature_quality: high
[INFO]    feature_type: sift
[INFO]    force_gps: False
[INFO]    gcp: None
[INFO]    geo: None
[INFO]    gps_accuracy: 10
[INFO]    ignore_gsd: False
[INFO]    matcher_distance: 0
[INFO]    matcher_neighbors: 8
[INFO]    matcher_type: flann
[INFO]    max_concurrency: 24
[INFO]    merge: all
[INFO]    mesh_octree_depth: 11
[INFO]    mesh_size: 200000
[INFO]    min_num_features: 8000
[INFO]    name: test
[INFO]    optimize_disk_space: False
[INFO]    orthophoto_compression: DEFLATE
[INFO]    orthophoto_cutline: False
[INFO]    orthophoto_kmz: False
[INFO]    orthophoto_no_tiled: False
[INFO]    orthophoto_png: False
[INFO]    orthophoto_resolution: 5
[INFO]    pc_classify: False
[INFO]    pc_csv: False
[INFO]    pc_ept: False
[INFO]    pc_filter: 2.5
[INFO]    pc_geometric: False
[INFO]    pc_las: False
[INFO]    pc_quality: medium
[INFO]    pc_rectify: False
[INFO]    pc_sample: 0
[INFO]    pc_tile: False
[INFO]    primary_band: auto
[INFO]    project_path: /
[INFO]    radiometric_calibration: none
[INFO]    rerun: None
[INFO]    rerun_all: False
[INFO]    rerun_from: None
[INFO]    resize_to: 2048
[INFO]    skip_3dmodel: False
[INFO]    skip_band_alignment: False
[INFO]    skip_report: False
[INFO]    sm_cluster: None
[INFO]    smrf_scalar: 1.25
[INFO]    smrf_slope: 0.15
[INFO]    smrf_threshold: 0.5
[INFO]    smrf_window: 18.0
[INFO]    split: 999999
[INFO]    split_image_groups: None
[INFO]    split_overlap: 150
[INFO]    texturing_data_term: gmi
[INFO]    texturing_keep_unseen_faces: False
[INFO]    texturing_outlier_removal_type: gauss_clamping
[INFO]    texturing_skip_global_seam_leveling: False
[INFO]    texturing_skip_local_seam_leveling: False
[INFO]    texturing_tone_mapping: none
[INFO]    tiles: True
[INFO]    time: False
[INFO]    use_3dmesh: False
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    verbose: False
[INFO]    ==============
[INFO]    Running dataset stage
[INFO]    Loading dataset from: D:\test\images
[INFO]    Loading 6 images
[INFO]    Wrote images database: D:\test\images.json
[INFO]    Found 6 usable images
[INFO]    Parsing SRS header: WGS84 UTM 49N
[INFO]    Finished dataset stage
[INFO]    Running split stage
[INFO]    Normal dataset, will process all at once.
[INFO]    Finished split stage
[INFO]    Running merge stage
[INFO]    Normal dataset, nothing to merge.
[INFO]    Finished merge stage
[INFO]    Running opensfm stage
[INFO]    Writing exif overrides
[INFO]    Maximum photo dimensions: 4864px
[INFO]    Photo dimensions for feature extraction: 2432px
[INFO]    Altitude data detected, enabling it for GPS alignment
[INFO]    ['use_exif_size: no', 'flann_algorithm: KDTREE', 'feature_process_size: 2432', 'feature_min_frames: 8000', 'processes: 24', 'matching_gps_neighbors: 8', 'matching_gps_distance: 0', 'optimize_camera_parameters: yes', 'undistorted_image_format: tif', 'bundle_outlier_filtering_type: AUTO', 'sift_peak_threshold: 0.066', 'align_orientation_prior: vertical', 'triangulation_type: ROBUST', 'retriangulation_ratio: 2', 'matcher_type: FLANN', 'feature_type: SIFT', 'use_altitude_tag: yes', 'align_method: auto', 'local_bundle_radius: 0']
[INFO]    Wrote reference_lla.json
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm extract_metadata "D:\test\opensfm"
2021-12-19 23:54:18,786 INFO: Extracting EXIF for 100_0001_0082.JPG
2021-12-19 23:54:18,863 INFO: Extracting EXIF for 100_0001_0083.JPG
2021-12-19 23:54:18,930 INFO: Extracting EXIF for 100_0001_0084.JPG
2021-12-19 23:54:18,990 INFO: Extracting EXIF for 100_0001_0085.JPG
2021-12-19 23:54:19,051 INFO: Extracting EXIF for 100_0001_0086.JPG
2021-12-19 23:54:19,113 INFO: Extracting EXIF for 100_0001_0087.JPG
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm detect_features "D:\test\opensfm"
2021-12-19 23:54:20,548 INFO: Capping memory usage to ~ 2315.515625 MB
2021-12-19 23:54:20,548 INFO: Expecting to process 34 images.
2021-12-19 23:54:20,558 INFO: Reading data for image 100_0001_0082.JPG (queue-size=0
2021-12-19 23:54:20,558 INFO: Reading data for image 100_0001_0084.JPG (queue-size=0
2021-12-19 23:54:20,558 INFO: Reading data for image 100_0001_0086.JPG (queue-size=0
2021-12-19 23:54:20,931 INFO: Reading data for image 100_0001_0087.JPG (queue-size=1
2021-12-19 23:54:20,936 INFO: Reading data for image 100_0001_0083.JPG (queue-size=2
2021-12-19 23:54:20,941 INFO: Reading data for image 100_0001_0085.JPG (queue-size=1
2021-12-19 23:54:20,941 INFO: Extracting ROOT_SIFT features for image 100_0001_0086.JPG
2021-12-19 23:54:20,941 INFO: Extracting ROOT_SIFT features for image 100_0001_0084.JPG
2021-12-19 23:54:20,941 INFO: Extracting ROOT_SIFT features for image 100_0001_0082.JPG
2021-12-19 23:54:20,967 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:20,967 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:20,967 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:21,357 INFO: Extracting ROOT_SIFT features for image 100_0001_0087.JPG
2021-12-19 23:54:21,375 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:21,386 INFO: Extracting ROOT_SIFT features for image 100_0001_0085.JPG
2021-12-19 23:54:21,393 INFO: Finished reading images
2021-12-19 23:54:21,393 INFO: Extracting ROOT_SIFT features for image 100_0001_0083.JPG
2021-12-19 23:54:21,415 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:21,415 DEBUG: Computing sift with threshold 0.066
2021-12-19 23:54:23,677 DEBUG: Found 9839 points in 2.7090587615966797s
2021-12-19 23:54:23,678 DEBUG: done
2021-12-19 23:54:27,940 DEBUG: Found 10569 points in 6.964229583740234s
2021-12-19 23:54:27,948 DEBUG: done
2021-12-19 23:54:28,265 DEBUG: Found 11260 points in 7.296746730804443s
2021-12-19 23:54:28,265 DEBUG: done
2021-12-19 23:54:28,498 DEBUG: No segmentation for 100_0001_0082.JPG, no features masked.
2021-12-19 23:54:28,779 DEBUG: Found 11301 points in 7.403748273849487s
2021-12-19 23:54:28,780 DEBUG: done
2021-12-19 23:54:29,041 DEBUG: Found 9705 points in 7.6247475147247314s
2021-12-19 23:54:29,041 DEBUG: done
2021-12-19 23:54:29,083 DEBUG: No segmentation for 100_0001_0086.JPG, no features masked.
2021-12-19 23:54:29,228 DEBUG: Found 10096 points in 7.811746835708618s
2021-12-19 23:54:29,228 DEBUG: done
2021-12-19 23:54:29,355 DEBUG: No segmentation for 100_0001_0084.JPG, no features masked.
2021-12-19 23:54:29,764 DEBUG: No segmentation for 100_0001_0087.JPG, no features masked.
2021-12-19 23:54:29,930 DEBUG: No segmentation for 100_0001_0085.JPG, no features masked.
2021-12-19 23:54:30,082 DEBUG: No segmentation for 100_0001_0083.JPG, no features masked.
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm match_features "D:\test\opensfm"
2021-12-19 23:54:31,980 INFO: Matching 15 image pairs
2021-12-19 23:54:31,980 INFO: Computing pair matching with 11 processes
2021-12-19 23:54:32,068 DEBUG: No segmentation for 100_0001_0082.JPG, no features masked.
2021-12-19 23:54:32,078 DEBUG: No segmentation for 100_0001_0083.JPG, no features masked.
2021-12-19 23:54:32,080 DEBUG: No segmentation for 100_0001_0086.JPG, no features masked.
2021-12-19 23:54:32,083 DEBUG: No segmentation for 100_0001_0085.JPG, no features masked.
2021-12-19 23:54:32,089 DEBUG: No segmentation for 100_0001_0087.JPG, no features masked.
2021-12-19 23:54:32,135 DEBUG: No segmentation for 100_0001_0084.JPG, no features masked.
2021-12-19 23:54:32,526 DEBUG: Matching 100_0001_0083.JPG and 100_0001_0087.JPG.  Matcher: FLANN (symmetric) T-desc: 0.527 T-robust: 0.010 T-total: 0.539 Matches: 2050 Robust: 2017 Success: True
2021-12-19 23:54:32,666 DEBUG: Matching 100_0001_0082.JPG and 100_0001_0085.JPG.  Matcher: FLANN (symmetric) T-desc: 0.673 T-robust: 0.004 T-total: 0.679 Matches: 1553 Robust: 1520 Success: True
2021-12-19 23:54:32,722 DEBUG: Matching 100_0001_0083.JPG and 100_0001_0086.JPG.  Matcher: FLANN (symmetric) T-desc: 0.729 T-robust: 0.004 T-total: 0.735 Matches: 2116 Robust: 2098 Success: True
2021-12-19 23:54:32,750 DEBUG: Matching 100_0001_0086.JPG and 100_0001_0085.JPG.  Matcher: FLANN (symmetric) T-desc: 0.752 T-robust: 0.005 T-total: 0.762 Matches: 2922 Robust: 2908 Success: True
2021-12-19 23:54:32,766 DEBUG: Matching 100_0001_0083.JPG and 100_0001_0085.JPG.  Matcher: FLANN (symmetric) T-desc: 0.771 T-robust: 0.005 T-total: 0.779 Matches: 2083 Robust: 2050 Success: True
2021-12-19 23:54:32,778 DEBUG: Matching 100_0001_0086.JPG and 100_0001_0082.JPG.  Matcher: FLANN (symmetric) T-desc: 0.786 T-robust: 0.003 T-total: 0.791 Matches: 1591 Robust: 1563 Success: True
2021-12-19 23:54:32,830 DEBUG: Matching 100_0001_0086.JPG and 100_0001_0087.JPG.  Matcher: FLANN (symmetric) T-desc: 0.834 T-robust: 0.006 T-total: 0.843 Matches: 3096 Robust: 3079 Success: True
2021-12-19 23:54:32,854 DEBUG: Matching 100_0001_0087.JPG and 100_0001_0085.JPG.  Matcher: FLANN (symmetric) T-desc: 0.852 T-robust: 0.014 T-total: 0.868 Matches: 2122 Robust: 2097 Success: True
2021-12-19 23:54:32,861 DEBUG: Matching 100_0001_0086.JPG and 100_0001_0084.JPG.  Matcher: FLANN (symmetric) T-desc: 0.862 T-robust: 0.010 T-total: 0.875 Matches: 2785 Robust: 2768 Success: True
2021-12-19 23:54:32,940 DEBUG: Matching 100_0001_0085.JPG and 100_0001_0084.JPG.  Matcher: FLANN (symmetric) T-desc: 0.944 T-robust: 0.006 T-total: 0.953 Matches: 3100 Robust: 3083 Success: True
2021-12-19 23:54:32,958 DEBUG: Matching 100_0001_0087.JPG and 100_0001_0082.JPG.  Matcher: FLANN (symmetric) T-desc: 0.427 T-robust: 0.003 T-total: 0.431 Matches: 1589 Robust: 1559 Success: True
2021-12-19 23:54:32,964 DEBUG: Matching 100_0001_0087.JPG and 100_0001_0084.JPG.  Matcher: FLANN (symmetric) T-desc: 0.961 T-robust: 0.012 T-total: 0.976 Matches: 2507 Robust: 2485 Success: True
2021-12-19 23:54:32,999 DEBUG: Matching 100_0001_0082.JPG and 100_0001_0084.JPG.  Matcher: FLANN (symmetric) T-desc: 0.326 T-robust: 0.004 T-total: 0.332 Matches: 2248 Robust: 2228 Success: True
2021-12-19 23:54:33,031 DEBUG: Matching 100_0001_0083.JPG and 100_0001_0082.JPG.  Matcher: FLANN (symmetric) T-desc: 0.272 T-robust: 0.005 T-total: 0.280 Matches: 3140 Robust: 3125 Success: True
2021-12-19 23:54:33,049 DEBUG: Matching 100_0001_0083.JPG and 100_0001_0084.JPG.  Matcher: FLANN (symmetric) T-desc: 0.319 T-robust: 0.005 T-total: 0.328 Matches: 3370 Robust: 3353 Success: True
2021-12-19 23:54:33,051 INFO: Matched 15 pairs (brown-brown: 15) in 1.0712107000000002 seconds (0.07141407333333333 seconds/pair).
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm create_tracks "D:\test\opensfm"
2021-12-19 23:54:34,520 INFO: reading features
2021-12-19 23:54:34,694 DEBUG: Merging features onto tracks
2021-12-19 23:54:34,857 DEBUG: Good tracks: 9972
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm reconstruct "D:\test\opensfm"
2021-12-19 23:54:36,804 INFO: Starting incremental reconstruction
2021-12-19 23:54:36,985 INFO: Starting reconstruction with 100_0001_0082.JPG and 100_0001_0084.JPG
2021-12-19 23:54:37,084 INFO: Two-view reconstruction inliers: 2593 / 2594
2021-12-19 23:54:37,303 INFO: Triangulated: 2593
2021-12-19 23:54:37,942 DEBUG: Ceres Solver Report: Iterations: 15, Initial cost: 1.731384e+02, Final cost: 1.266521e+01, Termination: CONVERGENCE
2021-12-19 23:54:37,996 INFO: Removed outliers: 251
2021-12-19 23:54:38,032 INFO: -------------------------------------------------------
2021-12-19 23:54:38,071 INFO: 100_0001_0083.JPG resection inliers: 1851 / 1852
2021-12-19 23:54:38,098 INFO: Adding 100_0001_0083.JPG to the reconstruction
2021-12-19 23:54:38,319 INFO: Re-triangulating
2021-12-19 23:54:38,323 WARNING: Shots and/or GCPs are aligned on a single-line. Using vertical prior
2021-12-19 23:54:38,748 DEBUG: Ceres Solver Report: Iterations: 14, Initial cost: 4.216533e+01, Final cost: 3.659444e+01, Termination: CONVERGENCE
2021-12-19 23:54:39,880 DEBUG: Ceres Solver Report: Iterations: 14, Initial cost: 4.877876e+01, Final cost: 3.733700e+01, Termination: CONVERGENCE
2021-12-19 23:54:40,018 INFO: Removed outliers: 424
2021-12-19 23:54:40,024 INFO: -------------------------------------------------------
2021-12-19 23:54:40,075 INFO: 100_0001_0086.JPG resection inliers: 2281 / 2282
2021-12-19 23:54:40,099 INFO: Adding 100_0001_0086.JPG to the reconstruction
2021-12-19 23:54:40,258 INFO: Shots and/or GCPs are well-conditioned. Using naive 3D-3D alignment.
2021-12-19 23:54:40,896 DEBUG: Ceres Solver Report: Iterations: 16, Initial cost: 1.132658e+02, Final cost: 5.233741e+01, Termination: CONVERGENCE
2021-12-19 23:54:41,077 INFO: Removed outliers: 423
2021-12-19 23:54:41,085 INFO: -------------------------------------------------------
2021-12-19 23:54:41,133 INFO: 100_0001_0087.JPG resection inliers: 2878 / 2885
2021-12-19 23:54:41,162 INFO: Adding 100_0001_0087.JPG to the reconstruction
2021-12-19 23:54:41,305 INFO: Shots and/or GCPs are well-conditioned. Using naive 3D-3D alignment.
2021-12-19 23:54:41,836 DEBUG: Ceres Solver Report: Iterations: 8, Initial cost: 9.881945e+01, Final cost: 6.957699e+01, Termination: CONVERGENCE
2021-12-19 23:54:42,070 INFO: Removed outliers: 528
2021-12-19 23:54:42,080 INFO: -------------------------------------------------------
2021-12-19 23:54:42,137 INFO: 100_0001_0085.JPG resection inliers: 3314 / 3315
2021-12-19 23:54:42,171 INFO: Adding 100_0001_0085.JPG to the reconstruction
2021-12-19 23:54:42,313 INFO: -------------------------------------------------------
2021-12-19 23:54:42,314 INFO: Shots and/or GCPs are well-conditioned. Using naive 3D-3D alignment.
2021-12-19 23:54:43,155 DEBUG: Ceres Solver Report: Iterations: 11, Initial cost: 1.178669e+02, Final cost: 1.005176e+02, Termination: CONVERGENCE
2021-12-19 23:54:43,442 INFO: Removed outliers: 637
2021-12-19 23:54:43,526 INFO: Reconstruction 0: 6 images, 9627 points
2021-12-19 23:54:43,526 INFO: 1 partial reconstructions in total.
[INFO]    Export reconstruction stats
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm compute_statistics --diagram_max_points 100000 "D:\test\opensfm"
2021-12-19 23:54:48,809 DEBUG: locator: <matplotlib.colorbar._ColorbarAutoLocator object at 0x000001DC067DE820>
2021-12-19 23:54:48,809 DEBUG: Using auto colorbar locator <matplotlib.colorbar._ColorbarAutoLocator object at 0x000001DC067DE820> on colorbar
2021-12-19 23:54:48,809 DEBUG: Setting pcolormesh
2021-12-19 23:54:49,401 DEBUG: locator: <matplotlib.colorbar._ColorbarAutoLocator object at 0x000001DC06E40D90>
2021-12-19 23:54:49,401 DEBUG: Using auto colorbar locator <matplotlib.colorbar._ColorbarAutoLocator object at 0x000001DC06E40D90> on colorbar
2021-12-19 23:54:49,401 DEBUG: Setting pcolormesh
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm export_geocoords --reconstruction --proj "+proj=utm +zone=49 +datum=WGS84 +units=m +no_defs +type=crs" --offset-x 533324.0 --offset-y 3013303.0 "D:\test\opensfm"
[INFO]    Updating D:\test\opensfm\config.yaml
[INFO]    undistorted_image_max_size: 2849
[INFO]    Undistorting D:\test\opensfm ...
2021-12-19 23:54:55,323 DEBUG: Undistorting image 100_0001_0082.JPG
2021-12-19 23:54:55,323 DEBUG: Undistorting image 100_0001_0084.JPG
2021-12-19 23:54:55,323 DEBUG: Undistorting image 100_0001_0086.JPG
2021-12-19 23:54:55,324 DEBUG: Undistorting image 100_0001_0085.JPG
2021-12-19 23:54:55,324 DEBUG: Undistorting image 100_0001_0087.JPG
2021-12-19 23:54:55,323 DEBUG: Undistorting image 100_0001_0083.JPG
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm export_visualsfm --points "D:\test\opensfm"
[INFO]    Finished opensfm stage
[INFO]    Running openmvs stage
[INFO]    running D:\ODM\SuperBuild\install\bin\opensfm\bin\opensfm export_openmvs "D:\test\opensfm"
[INFO]    Running dense reconstruction. This might take a while.
[INFO]    Estimating depthmaps
[INFO]    running D:\ODM\SuperBuild\install\bin\OpenMVS\DensifyPointCloud "D:\test\opensfm\undistorted\openmvs\scene.mvs"  --resolution-level 2 --min-resolution 608 --max-resolution 2849 --max-threads 24 --number-views-fuse 2 -w "D:\test\opensfm\undistorted\openmvs\depthmaps" -v 0 --geometric-iters 0
23:55:02 [App     ] Build date: Dec  3 2021, 18:37:55
23:55:02 [App     ] CPU: AMD Ryzen 9 3900X 12-Core Processor             (24 cores)
23:55:02 [App     ] RAM: 15.91GB Physical Memory 128.00TB Virtual Memory
23:55:02 [App     ] OS: Windows 8 x64
23:55:02 [App     ] SSE & AVX compatible CPU & OS detected
23:55:02 [App     ] Command line: D:\test\opensfm\undistorted\openmvs\scene.mvs --resolution-level 2 --min-resolution 608 --max-resolution 2849 --max-threads 24 --number-views-fuse 2 -w D:\test\opensfm\undistorted\openmvs\depthmaps -v 0 --geometric-iters 0
23:55:03 [App     ] Preparing images for dense reconstruction completed: 6 images (185ms)
23:55:03 [App     ] Selecting images for dense reconstruction completed: 6 images (2ms)
Estimated depth-maps 6 (100%, 515ms)
Filtered depth-maps 6 (100%, 210ms)
Fused depth-maps 6 (100%, 486ms)
23:55:04 [App     ] Densifying point-cloud completed: 412105 points (1s452ms)
23:55:05 [App     ] MEMORYINFO: {
23:55:05 [App     ]     PageFaultCount 232253
23:55:05 [App     ]     PeakWorkingSetSize 301.63MB
23:55:05 [App     ]     WorkingSetSize 213.21MB
23:55:05 [App     ]     QuotaPeakPagedPoolUsage 427.09KB
23:55:05 [App     ]     QuotaPagedPoolUsage 421.84KB
23:55:05 [App     ]     QuotaPeakNonPagedPoolUsage 37.71KB
23:55:05 [App     ]     QuotaNonPagedPoolUsage 25.49KB
23:55:05 [App     ]     PagefileUsage 504.94MB
23:55:05 [App     ]     PeakPagefileUsage 590.18MB
23:55:05 [App     ] } ENDINFO
[INFO]    running D:\ODM\SuperBuild\install\bin\OpenMVS\DensifyPointCloud --filter-point-cloud -1 -i "D:\test\opensfm\undistorted\openmvs\scene_dense.mvs" -v 0
23:55:05 [App     ] Build date: Dec  3 2021, 18:37:55
23:55:05 [App     ] CPU: AMD Ryzen 9 3900X 12-Core Processor             (24 cores)
23:55:05 [App     ] RAM: 15.91GB Physical Memory 128.00TB Virtual Memory
23:55:05 [App     ] OS: Windows 8 x64
23:55:05 [App     ] SSE & AVX compatible CPU & OS detected
23:55:05 [App     ] Command line: --filter-point-cloud -1 -i D:\test\opensfm\undistorted\openmvs\scene_dense.mvs -v 0
Point visibility checks 412105 (100%, 2s308ms)
23:55:08 [App     ] MEMORYINFO: {
23:55:08 [App     ]     PageFaultCount 37655
23:55:08 [App     ]     PeakWorkingSetSize 128.56MB
23:55:08 [App     ]     WorkingSetSize 123.38MB
23:55:08 [App     ]     QuotaPeakPagedPoolUsage 410.20KB
23:55:08 [App     ]     QuotaPagedPoolUsage 410.20KB
23:55:08 [App     ]     QuotaPeakNonPagedPoolUsage 22.16KB
23:55:08 [App     ]     QuotaNonPagedPoolUsage 21.91KB
23:55:08 [App     ]     PagefileUsage 217.14MB
23:55:08 [App     ]     PeakPagefileUsage 221.71MB
23:55:08 [App     ] } ENDINFO
[INFO]    Finished openmvs stage
[INFO]    Running odm_filterpoints stage
[INFO]    Filtering D:\test\opensfm\undistorted\openmvs\scene_dense_dense_filtered.ply (statistical, meanK 16, standard deviation 2.5)
[INFO]    running pdal pipeline -i "C:\Users\Administrator\AppData\Local\Temp\tmpzub0vppe.json"
PDAL: bad conversion

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 1
Traceback (most recent call last):
  File "D:\ODM\stages\odm_app.py", line 94, in execute
    self.first_stage.run()
  File "D:\ODM\opendm\types.py", line 346, in run
    self.next_stage.run(outputs)
  File "D:\ODM\opendm\types.py", line 346, in run
    self.next_stage.run(outputs)
  File "D:\ODM\opendm\types.py", line 346, in run
    self.next_stage.run(outputs)
  [Previous line repeated 2 more times]
  File "D:\ODM\opendm\types.py", line 327, in run
    self.process(self.args, outputs)
  File "D:\ODM\stages\odm_filterpoints.py", line 39, in process
    point_cloud.filter(inputPointCloud, tree.filtered_point_cloud,
  File "D:\ODM\opendm\point_cloud.py", line 176, in filter
    run_pipeline(pipeline, verbose=verbose)
  File "D:\ODM\opendm\dem\pdal.py", line 161, in run_pipeline
    system.run(' '.join(cmd))
  File "D:\ODM\opendm\system.py", line 106, in run
    raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 1

===== Done, human-readable information to follow... =====

[ERROR]   Uh oh! Processing stopped because of strange values in the reconstruction. This is often a sign that the input data has some issues or the software cannot deal with it. Have you followed best practices for data acquisition? See https://docs.opendronemap.org/flying/

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

none

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

none

**Comment by pierotofy** [comment]
>  If possible please include a copy of your dataset uploaded on Google Drive or Dropbox.

**Comment by pierotofy** [comment]
We cannot fix this unless we can access a dataset. Can you share a dataset?

**Comment by pierotofy** [comment]
Closing since a dataset cannot be accessed and that code path has been removed in `2.7.0` anyway (we now invoke the `FPCFilter` module for odm_filterpoints). 🙏
