### ISSUE TITLE
[python port] If the last argument does not have a value (e.g. --help) then run.py will fail

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#152]
```
dmb2@Latitude-E5550:~/Documents/ODM$ run.py --help
Traceback (most recent call last):
  File "run.py", line 986, in <module>
    parseArgs()
  File "run.py", line 76, in parseArgs
    if not re.search("^--[^a-z\-]*", sys.argv[i + 1]):
IndexError: list index out of range
```

if I run `run.py --help a`, it executes successfully.

**Comment by dakotabenjamin** [comment]
I cleaned up argument parsing by using argpart in #158.
