### ISSUE TITLE
OpenSfM read exif error

### ISSUE THREAD

**Issue by xialang2012** [OpenDroneMap/ODM#318]
Hi, @paulinus 

I try to run 
`./run.py --project-path /home/xl/open/images/ts-uhd/`
is shows

> Traceback (most recent call last):
>   File "./run.py", line 36, in <module>
>     plasm.execute(niter=1)
>   File "/home/xl/odm-new/odm-mvs/OpenDroneMap/scripts/dataset.py", line 57, in process
>     self.params.force_ccd)
>   File "/home/xl/odm-new/odm-mvs/OpenDroneMap/opendm/types.py", line 32, in **init**
>     self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
>   File "/home/xl/odm-new/odm-mvs/OpenDroneMap/opendm/types.py", line 73, in parse_pyexiv2_values
>     self.make_model = sensor_string(self.camera_make, self.camera_model)
>   File "/home/xl/odm-new/odm-mvs/OpenDroneMap/SuperBuild/src/opensfm/opensfm/exif.py", line 63, in sensor_string
>     model = model.replace(make, '') # remove possible duplicate 'make' information in 'model' for better matching
> TypeError: expected a character buffer object

**Comment by xialang2012** [comment]
When the openSfM failed to get the name, a string of 'none' was returned, and the 
ODM failed to recognize it.
