### ISSUE TITLE
I am getting stacked in running opensfm with this command "bin/run_all data/lund" which I am getting this error anyone help

### ISSUE THREAD

**Issue by dawit3526** [OpenDroneMap/ODM#381]
File "/home/dawit/OpenSfM-master/bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/dawit/OpenSfM-master/opensfm/commands/**init**.py", line 2, in <module>
    import extract_metadata
  File "/home/dawit/OpenSfM-master/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/dawit/OpenSfM-master/opensfm/dataset.py", line 9, in <module>
    import networkx as nx
ImportError: No module named networkx
root@dawit-N550LF:/home/dawit/OpenSfM-master# python ./bin/opensfm detect_features data/lund/
Traceback (most recent call last):
  File "./bin/opensfm", line 10, in <module>
    from opensfm import commands
  File "/home/dawit/OpenSfM-master/opensfm/commands/**init**.py", line 2, in <module>
    import extract_metadata
  File "/home/dawit/OpenSfM-master/opensfm/commands/extract_metadata.py", line 5, in <module>
    from opensfm import dataset
  File "/home/dawit/OpenSfM-master/opensfm/dataset.py", line 9, in <module>
    import networkx as nx
ImportError: No module named networkx

**Comment by dakotabenjamin** [comment]
I don't understand what you are trying to do here. Can you provide more clarification?

**Comment by dakotabenjamin** [comment]
This issue is outdated and will be closed. Please open a new thread in http://community.opendronemap.org and reference this issue if you would like to continue the conversation.
