### ISSUE TITLE
Previous matching data not reset properly when rerunning

### ISSUE THREAD

**Issue by pulquero** [OpenDroneMap/ODM#423]
While trying the latest dev branch I get the following error (2 cpus):

>
2016-11-19 02:05:48,212 2016_1023_152236_060_geotag.jpg - 2016_1103_222313_651_geotag.jpg has 0 candidate matches
2016-11-19 02:05:50,049 2016_1103_220835_212_geotag.jpg - 2016_1103_222029_569_geotag.jpg has 2 candidate matches
2016-11-19 02:05:54,753 2016_1023_152236_060_geotag.jpg - 2016_1103_220325_057_geotag.jpg has 2 candidate matches
Traceback (most recent call last):
  File "/opt/odm/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/opt/odm/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 44, in run
    p.map(match, args)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 22] Invalid argument
2016-11-19 02:05:54,850 Matching 2016_1102_234045_113_geotag.jpg  -  345 / 1369
[ERROR]   quitting cause: 
	PYTHONPATH=/opt/odm/SuperBuild/install/lib/python2.7/dist-packages /opt/odm/SuperBuild/src/opensfm/bin/run_all /mnt/data/agavefield_all/opensfm
returned with code 256.

With a single cpu:

>
Traceback (most recent call last):
  File "/opt/odm/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/opt/odm/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 42, in run
    match(arg)
  File "/opt/odm/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 189, in match
    p2, f2, c2 = ctx.data.load_features(im2)
  File "/opt/odm/SuperBuild/src/opensfm/opensfm/dataset.py", line 217, in load_features
    s = np.load(self.__feature_file(image))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 392, in load
    fid.seek(-N, 1)  # back-up
IOError: [Errno 22] Invalid argument
[ERROR]   quitting cause: 
	PYTHONPATH=/opt/odm/SuperBuild/install/lib/python2.7/dist-packages /opt/odm/SuperBuild/src/opensfm/bin/run_all /mnt/data/agavefield_all/opensfm
returned with code 256.

**Comment by pulquero** [comment]
After syncing I reran configure.sh but maybe I need to do a 'clean' first?

**Comment by pulquero** [comment]
After clearing down all the results directories it worked without problems, so I believe the problem is --rerun-all doesn't clean down some previous output from matching properly.
