### ISSUE TITLE
Exception: Child returned 137

### ISSUE THREAD

**Issue by piousgreek** [OpenDroneMap/ODM#474]
I have been getting good results and have been playing with various parameters to determine how they impact quality and computational time.  Anyhow, does anybody know what this exception means?  I do not get this error with default parameters so obviously something i tweaked didn't go well.  

python run.py --orthophoto-resolution 100 --force-focal 3.97  --pmvs-csize 1 --pmvs-wsize 8 --mesh-size 600000 --mesh-octree-depth 16 --time --project-path /home/siddhartha/Desktop/quickwork/geotagged

[INFO]    Running ODM PMVS Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM Mesh file in: /quickwork/geotagged2/odm_meshing/odm_mesh.ply
[DEBUG]   running /OpenDroneMap/build/bin/odm_meshing -inputFile /quickwork/geotagged2/pmvs/recon0/models/option-0000.ply -outputFile /quickwork/geotagged2/odm_meshing/odm_mesh.ply -logFile /quickwork/geotagged2/odm_meshing/odm_meshing_log.txt -maxVertexCount 600000 -octreeDepth 16  -samplesPerNode 1.0 -solverDivide 9
Killed
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    plasm.execute(niter=1)
  File "/OpenDroneMap/scripts/odm_meshing.py", line 74, in process
    '-samplesPerNode {samples} -solverDivide {solver}'.format(**kwargs))
  File "/OpenDroneMap/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137

**Comment by piousgreek** [comment]
appears to be answered here:

https://github.com/OpenDroneMap/OpenDroneMap/issues/445
