### ISSUE TITLE
Merging depthmaps error

### ISSUE THREAD

**Issue by naivefun** [OpenDroneMap/ODM#625]
I'm using data from dronedeploy and see the errors:
```
2017-07-10 03:02:00,688 Cleaning depthmap for image DJI_0087.JPG
2017-07-10 03:02:01,156 Cleaning depthmap for image DJI_0051.JPG
2017-07-10 03:02:01,758 Merging depthmaps
Killed
Traceback (most recent call last):
  File "/code/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 128, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 137
```

Any way to fix this? Thanks.

**Comment by naivefun** [comment]
Seems an out of resource error.
