### ISSUE TITLE
Docker -> OSError: [Errno 13] Permission denied: '/code/images'

### ISSUE THREAD

**Issue by PeterSprague** [OpenDroneMap/ODM#635]
I have both built the docker image and downloaded from docker.io.  When run from ODM dir with:
$ sudo docker run -it --rm -v $(pwd)/images:/code/images -v $(pwd)/odm_orthophoto:/code/odm_orthophoto -v $(pwd)/odm_texturing:/code/odm_texturing opendronemap/opendronemap

Console output:
[INFO]    Initializing OpenDroneMap app - Mon Jul 24 18:59:14  2017
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /code/images
[DEBUG]   /code/images
Traceback (most recent call last):
  File "/code/run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/dataset.py", line 67, in process
    files = get_images(images_dir)
  File "/code/scripts/dataset.py", line 42, in get_images
    return [f for f in io.get_files_list(in_dir) if supported_extension(f)]
  File "/code/opendm/io.py", line 6, in get_files_list
    return os.listdir(path_dir)
OSError: [Errno 13] Permission denied: '/code/images'

Volume dir structure:  ODM/images/
Tried with image dir file permissions 777
Tried with image dir ownership set to root

**Comment by PeterSprague** [comment]
Running Fedora 26 with Selinux enabled is the cause of the issue.
Solution:
$ sudo docker run -it -v $(pwd)/images:/code/images:Z --entrypoint=/bin/bash  --rm opendronemap/opendronemap

As per: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
