### ISSUE TITLE
Error while running with video SLAM

### ISSUE THREAD

**Issue by Ntweat** [OpenDroneMap/ODM#679]
Hi 
I tried to run opendrone on a video
I got the following
```
~/openDrone/OpenDroneMap_v0_3_1$ python run.py --project-path ~/openDrone/slam/ --video room003_2017-09-26_173208000.MOV --slam-config config.yaml --resize-to 1920
usage: run.py [options] <project name>
run.py: error: too few arguments
```

**Comment by Ntweat** [comment]
Update: 
I tried adding a random name at the end. It started but gave the following error

```
~/openDrone/OpenDroneMap_v0_3_1$ python run.py --project-path ~/openDrone/slam/ --video room003_2017-09-26_173208000.MOV --slam-config config.yaml --resize-to 1920 snn
[INFO]    Initializing OpenDroneMap app - Thu Sep 28 17:45:13  2017
[WARNING] Directory snn does not exist. Creating it now.
[INFO]    Running OMD Slam Cell
[DEBUG]   running cd /home/ntweat/openDrone/slam/snn/opensfm && /home/ntweat/openDrone/OpenDroneMap_v0_3_1/build/bin/odm_slam /home/ntweat/openDrone/OpenDroneMap_v0_3_1/SuperBuild/src/orb_slam2/Vocabulary/ORBvoc.txt /home/ntweat/openDrone/slam/snn/config.yaml /home/ntweat/openDrone/slam/snn/room003_2017-09-26_173208000.MOV
/bin/sh: 1: /home/ntweat/openDrone/OpenDroneMap_v0_3_1/build/bin/odm_slam: not found
Traceback (most recent call last):
  File "run.py", line 46, in <module>
```

The make command for slam ran successfully and gave no errors.
But there is no file called odm_slam in bin directory

**Comment by Ntweat** [comment]
Update:
I edited the cmake file and set the ODM_BUILD_SLAM to ON manually.

But now I am getting the following error

```
~/openDrone/OpenDroneMap_v0_3_1$ python run.py --project-path ~/openDrone/slam/ --video room003_2017-09-26_173208000.MOV --slam-config config.yaml --resize-to 1920 sdf
[INFO]    Initializing OpenDroneMap app - Thu Sep 28 18:06:55  2017
[INFO]    Running OMD Slam Cell
[DEBUG]   running cd /home/ntweat/openDrone/slam/sdf/opensfm && /home/ntweat/openDrone/OpenDroneMap_v0_3_1/build/bin/odm_slam /home/ntweat/openDrone/OpenDroneMap_v0_3_1/SuperBuild/src/orb_slam2/Vocabulary/ORBvoc.txt /home/ntweat/openDrone/slam/sdf/config.yaml /home/ntweat/openDrone/slam/sdf/room003_2017-09-26_173208000.MOV
Failed to load video: /home/ntweat/openDrone/slam/sdf/room003_2017-09-26_173208000.MOV
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    plasm.execute(niter=1)
  File "/home/ntweat/openDrone/OpenDroneMap_v0_3_1/scripts/odm_slam.py", line 61, in process
    video,
  File "/home/ntweat/openDrone/OpenDroneMap_v0_3_1/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 255

```

EDIT:
As the config.yaml link on opendrone site was broken I am using this https://github.com/raulmur/ORB_SLAM2/blob/master/Examples/Monocular/EuRoC.yaml as base and edited the camera parameters.
