### ISSUE TITLE
Cannot process exif headers with UTF-16 encoding

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#732]
Related discussion with sample dataset: http://community.opendronemap.org/t/unicodedecodeerror/145/3

```
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/dataset.py", line 72, in process
    photos += [make_odm_photo(self.params.force_focal, self.params.force_ccd, files)]
  File "/code/scripts/dataset.py", line 17, in make_odm_photo
    force_ccd)
  File "/code/opendm/types.py", line 35, in __init__
    self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
  File "/code/opendm/types.py", line 110, in parse_pyexiv2_values
    key = [x for x in ccd_widths.keys() if self.make_model in x]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 0: ordinal not in range(128)
```

Possible solutions would involve supporting reading UTF-16 strings or at a minimum skip reading the values and continue processing.

**Comment by pierotofy** [comment]
This should be fixed.
