### ISSUE TITLE
Exception: Child returned 139

### ISSUE THREAD

**Issue by SundaresanN** [OpenDroneMap/ODM#819]
Hi, i have installed opendronemap natively by running configure.sh install , it works fine after installing. it produces all output except DTM, **so i changed dtm = True in settings.yaml and i run ./run.sh -i tests/test_data/images/ test_dsm** ,  but it produces error like 

[INFO]    Running ODM Georeferencing Cell - Finished
[INFO]    Running ODM DEM Cell
[INFO]    Classify: True
[INFO]    Create DSM: False
[INFO]    Create DTM: True
[INFO]    DEM input file /home/ubuntu/odm/test_dsm/odm_georeferencing/odm_georeferenced_model.las found: True
[INFO]    Creating ../odm/test_dsm/odm_dem/dtm_r0.1 [idw] from 1 files
[DEBUG]   running pdal pipeline -i /tmp/tmpnhkTJL.json > /dev/null 2>&1
Traceback (most recent call last):
  File "/home/ubuntu/OpenDroneMap/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/home/ubuntu/OpenDroneMap/scripts/odm_dem.py", line 108, in process
    verbose=args.verbose
  File "/home/ubuntu/OpenDroneMap/opendm/dem/commands.py", line 32, in create_dems
    radius=rad, outdir=outdir, suffix=suffix, resolution=resolution, **kwargs))
  File "/home/ubuntu/OpenDroneMap/opendm/dem/commands.py", line 82, in create_dem
    pdal.run_pipeline(json, verbose=verbose)
  File "/home/ubuntu/OpenDroneMap/opendm/dem/pdal.py", line 222, in run_pipeline
    out = system.run(' '.join(cmd) + ' > /dev/null 2>&1')
  File "/home/ubuntu/OpenDroneMap/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139

 To fix error i tried rerun from odm_georeferencing **./run.sh -r odm_georeferencing -i tests/test_data/images/ test_dsm**  but no luck , I'm sure with --dtm or --dsm also produces same error. But i need DTM now. Thank you so much for great work.

**Comment by SundaresanN** [comment]
[test_dtm_log.txt](https://github.com/OpenDroneMap/OpenDroneMap/files/1988845/test_dtm_log.txt)
Its the long output for reference
