### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by PeterSprague** [OpenDroneMap/ODM#826]
See https://github.com/OpenDroneMap/OpenDroneMap/issues/773

I'm now getting this exact same error after building with latest OpenSfM master on Atom j3455 IoT.  I also had to rebuild OpenGV with core2 flag - https://github.com/mapillary/OpenSfM/issues/325

Intermediate source images used for multi-stage Docker build were created on a amd64 workstation.  As per: https://github.com/OpenDroneMap/OpenDroneMap/issues/346 solution may be to build all images on Atom, but I loath building VTK etc source on Atom 4 core.

Fixed the missing unicode errors in io.py of OpenSfM - see https://github.com/mapillary/OpenSfM/issues/325.

2018-05-18 21:15:36,694 INFO: Pruning depthmap for image 2017_1016_133647_208.JPG
2018-05-18 21:15:48,718 INFO: Merging depthmaps
[DEBUG] running PYTHONPATH=/usr/local/lib/python2.7/dist-packages /usr/local/src/OpenSfM/bin/export_bundler /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/opensfm
[DEBUG] running PYTHONPATH=/usr/local/lib/python2.7/dist-packages /usr/local/src/OpenSfM/bin/opensfm export_geocoords /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/opensfm --transformation --proj '+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=10 '
[INFO] Running ODM OpenSfM Cell - Finished
[INFO] Running ODM Meshing Cell
[DEBUG] Writing ODM Mesh file in: /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/odm_meshing/odm_mesh.ply
[DEBUG] running /code/build/bin/odm_meshing -inputFile /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/opensfm/depthmaps/merged.ply -outputFile /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/odm_meshing/odm_mesh.ply -logFile /var/www/data/ca4e2822-8c35-4d3e-9c44-62b7c4088b8e/odm_meshing/odm_meshing_log.txt -maxVertexCount 30000 -octreeDepth 5 -verbose -samplesPerNode 1.0 -solverDivide 9
The number of samples per octree node was manually set to: 1
Numerical solver divisions was manually set to: 5
Illegal instruction (core dumped)
Traceback (most recent call last):
File "/code/run.py", line 47, in
plasm.execute(niter=1)
File "/code/scripts/odm_meshing.py", line 80, in process
'-samplesPerNode {samples} -solverDivide {solver}'.format(**kwargs))
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 132

**Comment by PeterSprague** [comment]
Rebuilt only ODM code w/o Superbuild or source builds on Atom.  Used multi-stage build to pull in VTK & other source builds image that was built on amd64 workstation.  OpenGV was rebuilt with core2 flag.

Same error

**Comment by PeterSprague** [comment]
Rebuilt all base, source and ODM images on Atom.  OpenGV with arch=native flag.  Successful ODM build of ortho et al.

While Atom j3455 processor is a 64bit amd64 cpu, it seems to prefer "native" compiles.
