### ISSUE TITLE
Automatically remove tmp directory when running mvs texturing

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#830]
Mvs texturing fails if its `tmp` directory already exists. Sometimes (if texturing fails) this directory is not cleared. Maybe we should?

```
Temporary directory "tmp" exists within the destination directory.
Cannot continue since this directory would be delete in the end.

Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/mvstex.py", line 133, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/code/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

**Comment by smathermather** [comment]
+1 -- I've been thinking this too.
