### ISSUE TITLE
stack trace with version released today

### ISSUE THREAD

**Issue by gravatite** [OpenDroneMap/ODM#891]
### How did you install OpenDroneMap? (Docker, natively, ...)?

docker.

I ran this set of images successfully with the latest in docker last week (2018/09/06), and I ran "docker pull opendronemap/opendronemap" to get the latest after the release announcement today to compare the output between the old and new versions.

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Not using a browser, running docker using the command on the website as a template:
 docker run -ti --rm -v /scratch0/SP_Crater/test2:/datasets/ opendronemap/opendronemap --project-path /datasets

### What is the problem?

There's a stack trace when it gets part way through, here's an excerpt from the console output:

[DEBUG]   Writing ODM 2.5D Mesh file in: /datasets/code/odm_meshing/odm_25dmesh.ply
[WARNING] Cannot calculate GSD, using requested resolution of 5.0
[INFO]    Created temporary directory: /datasets/code/odm_meshing/tmp
[INFO]    Creating DSM for 2.5D mesh
[INFO]    Creating ../datasets/code/odm_meshing/tmp/mesh_dsm_r0.141421356237 [idw] from 1 files
[DEBUG]   running pdal pipeline -i /tmp/tmp1XsMXt.json > /dev/null 2>&1
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 98, in process
    max_workers=args.max_concurrency)
  File "/code/opendm/mesh.py", line 35, in create_25dmesh
    max_workers=max_workers
  File "/code/opendm/dem/commands.py", line 38, in create_dems
    fouts = list(e.map(create_dem_for_radius, radius))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 783, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
    raise self._exception
Exception: Child returned 1

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

The latest version from last week ran to completion on this same set of images; my expectation was the code released today would also succeed and result in different output products that could be compared with the previous set.

For this run, I copied the images into a new test directory so it was running on an otherwise empty directory.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

I put the set of images I used last week into a new test directory and ran the above command to process them as a baseline without any extra parameters or other tuning.

**Comment by pierotofy** [comment]
Hey @gravatite thanks for reporting the issue.

Would it be possible for you to share your dataset with us (by uploading it on Google Drive or Dropbox)?

**Comment by pierotofy** [comment]
@gravatite are you still experiencing this issue?

**Comment by pierotofy** [comment]
Closing due to inactivity. This has been most likely fixed.
