### ISSUE TITLE
Automatically Skip Corrupted Files

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#931]
It would be an interesting enhancement to automatically detect and skip corrupted files at the beginning of the process (during dataset loading), without having to wait for a later stage of the pipeline to detect it. It seems to be a fairly common issue, especially when lower quality SD cards are used for data collection.

```
Processing view view_0054.mve...
Processing view view_0055.mve...
Error loading: /var/www/data/ca562c41-e579-4255-bd16-a2103a369669/images/DJI_0487.JPG
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/smvs.py", line 70, in process
system.run('%s %s %s' % (context.makescene_path, tree.mve_path, tree.smvs))
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

**Comment by pierotofy** [comment]
Fixed
