### ISSUE TITLE
GCP files with UTF-8 encoding throw errors

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#933]
```
[INFO]    Wrote images database: /var/www/data/eda1bb30-54e5-4c75-8f55-1726bd2e4dea/images.json
[INFO]    Found 18 usable images
[DEBUG]   Line: ﻿+proj=utm +zone=15 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/dataset.py", line 127, in process
outputs.reconstruction = types.ODM_Reconstruction(photos, coords_file=tree.odm_georeferencing_gcp)
File "/code/opendm/types.py", line 141, in __init__
self.projection = self.parse_coordinate_system(coords_file)
File "/code/opendm/types.py", line 168, in parse_coordinate_system
return Proj(line.strip('\''))
File "/usr/lib/python2.7/dist-packages/pyproj/__init__.py", line 358, in __new__
return _proj.Proj.__new__(self, projstring)
File "_proj.pyx", line 77, in _proj.Proj.__cinit__ (_proj.c:1099)
File "_proj.pyx", line 370, in _proj._strencode (_proj.c:3939)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

To reproduce:
 - Create a GCP file and save it with UTF-8 encoding

Process a dataset with the GCP file.

This should be improved.

**Comment by pierotofy** [comment]
This is fixed in the `speedimprov` branch.
