### ISSUE TITLE
clean install with opensfm problem detect features

### ISSUE THREAD

**Issue by katarias** [OpenDroneMap/ODM#940]
### How did you install OpenDroneMap? (Docker, natively, ...)?

OpendronMap from master branch Clean Install in Ubuntu 16.04 LTS

### What's your browser and operating system? 

Ubuntu 16.04 LTS

### What is the problem?
Failed on Opensfm detect_features module  - 

Traceback (most recent call last):
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
    command.run(args)
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/opensfm/commands/detect_features.py", line 30, in run
    parallel_map(detect, arguments, processes)
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/opensfm/context.py", line 38, in parallel_map
    return list(e.map(func, args))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 794, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
    raise self._exception
TypeError: expected str, bytes or os.PathLike object, not unicode

This was caused directly by 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 337, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/opensfm/commands/detect_features.py", line 78, in detect
    data.save_features(image, p_sorted, f_sorted, c_sorted)
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/opensfm/dataset.py", line 276, in save_features
    self.__save_features(self.__feature_file(image), image, points, descriptors, colors)
  File "/mnt/odm/odm-v0.4/SuperBuild/src/opensfm/opensfm/dataset.py", line 261, in __save_features
    colors=colors)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 691, in savez_compressed
    _savez(file, args, kwds, True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 700, in _savez
    file = os_fspath(file)
  File "/usr/local/lib/python2.7/dist-packages/numpy/compat/py3k.py", line 237, in os_fspath
    "not " + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not unicode
"""
Traceback (most recent call last):
  File "/mnt/odm/odm-v0.4/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/mnt/odm/odm-v0.4/scripts/run_opensfm.py", line 116, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/mnt/odm/odm-v0.4/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
FATAL ERROR: ODM Run failed with error code 0

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

Tried with different images set but throwing same error. It should process with opensfm fine.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Clean Install in fresh ubuntu 16.04 with "bash configure.sh install" and process images
bash run.sh --project-path images-path --matcher-neighbors 0 --min-num-features 8000 --start-with dataset --end-with odm_meshing project-id

**Comment by pierotofy** [comment]
Probably related https://github.com/OpenDroneMap/WebODM/issues/608

**Comment by pierotofy** [comment]
Yeah it's a problem affecting only native installs. Since `numpy` broke we tried to use the previous version, but in the `configure.sh` script the gippy component stealthy re-installs the newer broken version.

I've pushed a fix and I'm currently testing. If other people had the same issue, please `git pull origin master` and `bash configure.sh reinstall` and let us know if it works.

**Comment by katarias** [comment]
@pierotofy  Yes i also found issue with numpy latest version issue and was able to process it by applying numpy patch.
Thanks I am also able to process it after reinstall from master branch.
