### ISSUE TITLE
OpenDroneMapv0.4 execution on test data set

### ISSUE THREAD

**Issue by sk-123** [OpenDroneMap/ODM#942]
I installed OpenDroneMap-v0.4, installation was successful but when I am running OpenDroneMap on test data set "odm_data_aukerman" it is giving following error

Traceback (most recent call last):
  File "/home/Surendra/OpenDroneMap-v0.4/run.py", line 11, in <module>
    from scripts.odm_app import ODMApp
  File "/home/Surendra/OpenDroneMap-v0.4/scripts/odm_app.py", line 5, in <module>
    from opendm import types
  File "/home/Surendra/OpenDroneMap-v0.4/opendm/types.py", line 5, in <module>
    from opensfm.exif import sensor_string
ImportError: No module named opensfm.exif

I tried with different data set also but getting same error

Thanks

**Comment by pierotofy** [comment]
Hey @sk-123 :hand: sorry for the late reply; try to use the latest docker image. It should work.
