### ISSUE TITLE
MVE's makescene cannot handle filenames with spaces

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#951]
To reproduce, create a task with an image filename with a space (ex. 'DJI_0259 (2).JPG').

Observe as the program fails:

```
Processing view view_0000.mve...
Processing view view_0001.mve...
Error loading: /var/www/data/d671441f-63a2-43a0-baad-7bca40bc4bcc/images/DJI_0259
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/smvs.py", line 70, in process
system.run('%s %s %s' % (context.makescene_path, tree.mve_path, tree.smvs))
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

**Comment by smathermather** [comment]
😮
