### ISSUE TITLE
odm_cleanmesh not found

### ISSUE THREAD

**Issue by whatsuppiyush** [OpenDroneMap/ODM#960]
I was trying to run 
```python run.py -i /home/ppatel/clutter/odm/odm_ws/second_proj/images secII```
but I am getting this error again and again even after changing the resolution of images
How to FIX this
```
[INFO]    Filtering point cloud (statistical, meanK 16, standard deviation 2.5)
[WARNING] {} program not found. Will skip filtering, but this installation should be fixed.
[INFO]    Running ODM SMVS Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM Mesh file in: /home/ppatel/clutter/odm/odm_ws/secII/odm_meshing/odm_mesh.ply
[DEBUG]   running /home/ppatel/clutter/odm/ODM/SuperBuild/src/PoissonRecon/Bin/Linux/PoissonRecon --in /home/ppatel/clutter/odm/odm_ws/secII/smvs/smvs_dense_point_cloud.ply --out /home/ppatel/clutter/odm/odm_ws/secII/odm_meshing/odm_mesh.dirty.ply --depth 9 --pointWeight 4 --samplesPerNode 1.0 --threads 8 --linearFit 
[WARNING] Bad average root: 1.000000
	(0.492645 0.500067) (0.500067)
[WARNING] Bad average root: -0.000000
	(0.500067 0.395345) (0.500067)
[WARNING] Bad average root: -0.000000
	(0.500067 0.473916) (0.500067)
[DEBUG]   running /home/ppatel/clutter/odm/ODM/build/bin/odm_cleanmesh -inputFile /home/ppatel/clutter/odm/odm_ws/secII/odm_meshing/odm_mesh.dirty.ply -outputFile /home/ppatel/clutter/odm/odm_ws/secII/odm_meshing/odm_mesh.ply -removeIslands -decimateMesh 100000  
/bin/sh: 1: /home/ppatel/clutter/odm/ODM/build/bin/odm_cleanmesh: not found
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/home/ppatel/clutter/odm/ODM/scripts/odm_meshing.py", line 70, in process
    verbose=self.params.verbose)
  File "/home/ppatel/clutter/odm/ODM/opendm/mesh.py", line 142, in screened_poisson_reconstruction
    '-decimateMesh {max_vertex} {verbose} '.format(**cleanupArgs))
  File "/home/ppatel/clutter/odm/ODM/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 127```
-------------------------------------------

**Comment by pierotofy** [comment]
Something must have gone wrong with the installation (when running configure.sh). Navigate to `ODM/build` and run `make odm_cleanmesh`. If you get an error, you'll need to fix it to build the `odm_cleanmesh` program.
