### ISSUE TITLE
ODM failing with "ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/IO/PLY/vtkPLYWriter.cxx, line 114"

### ISSUE THREAD

**Issue by mshillinger** [OpenDroneMap/ODM#980]
### How did you install OpenDroneMap? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Ubuntu 16.04

### What is the problem?

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/IO/PLY/vtkPLYWriter.cxx, line 114
vtkPLYWriter (0x172ed30): No data to write!

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

These are just standard DJI generated images.  I would expect the process to finish or result in a descriptive error
++++++++++++++  Console OUTPUT ++++++++++++
docker run -it --rm -v "$(pwd)/images:/code/images" -v "$(pwd)/odm_orthophoto:/code/odm_orthophoto" -v "$(pwd)/odm_georeferencing:/code/odm_georeferencing" opendronemap/opendronemap
[INFO]    Initializing OpenDroneMap app - Wed Apr 24 13:15:41  2019
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /code/images
[DEBUG]   /code/images
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0032.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394711944 | lon: -81.5229665278 | alt: -63.148
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0036.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394675 | lon: -81.5227783889 | alt: -63.148
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0016.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.13948675 | lon: -81.5237216111 | alt: -63.148
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0020.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394828889 | lon: -81.523533 | alt: -63.148
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0028.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394751944 | lon: -81.5231550833 | alt: -63.248
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0024.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394793611 | lon: -81.5233443611 | alt: -63.148
[WARNING] Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
[DEBUG]   Loaded DJI_0012.JPG | camera: dji fc6510 | dimensions: 5472 x 3648 | focal: 8.8 | ccd: None | lat: 30.1394917222 | lon: -81.5239102222 | alt: -63.048
[INFO]    Wrote images database: /code/images.json
[INFO]    Found 7 usable images
[INFO]    Coordinates file already exist: /code/odm_georeferencing/coords.txt
[DEBUG]   Line: WGS84 UTM 17N
[INFO]    Running ODM Load Dataset Cell - Finished
[INFO]    Running ODM OpenSfM Cell
[DEBUG]   Altitude data detected, enabling it for GPS alignment
[DEBUG]   ['use_exif_size: no', 'feature_process_size: 2048', 'feature_min_frames: 8000', 'processes: 8', 'matching_gps_neighbors: 8', 'depthmap_method: PATCH_MATCH', 'depthmap_resolution: 640', 'depthmap_min_patch_sd: 1', 'depthmap_min_consistent_views: 3', 'optimize_camera_parameters: yes', 'use_altitude_tag: True', 'align_method: naive']
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm extract_metadata /code/opensfm
2019-04-24 13:15:43,199 INFO: Extracting EXIF for DJI_0032.JPG
2019-04-24 13:15:43,382 INFO: Extracting EXIF for DJI_0036.JPG
2019-04-24 13:15:43,562 INFO: Extracting EXIF for DJI_0016.JPG
2019-04-24 13:15:43,739 INFO: Extracting EXIF for DJI_0020.JPG
2019-04-24 13:15:43,918 INFO: Extracting EXIF for DJI_0028.JPG
2019-04-24 13:15:44,095 INFO: Extracting EXIF for DJI_0024.JPG
2019-04-24 13:15:44,273 INFO: Extracting EXIF for DJI_0012.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm detect_features /code/opensfm
2019-04-24 13:15:45,014 INFO: Extracting ROOT_HAHOG features for image DJI_0032.JPG
2019-04-24 13:15:45,209 INFO: Extracting ROOT_HAHOG features for image DJI_0036.JPG
2019-04-24 13:15:45,457 INFO: Extracting ROOT_HAHOG features for image DJI_0016.JPG
2019-04-24 13:15:45,716 INFO: Extracting ROOT_HAHOG features for image DJI_0020.JPG
2019-04-24 13:15:45,988 INFO: Extracting ROOT_HAHOG features for image DJI_0028.JPG
2019-04-24 13:15:46,262 INFO: Extracting ROOT_HAHOG features for image DJI_0024.JPG
2019-04-24 13:15:46,538 INFO: Extracting ROOT_HAHOG features for image DJI_0012.JPG
2019-04-24 13:15:49,125 DEBUG: Found 9940 points in 3.64647698402s
2019-04-24 13:15:49,711 DEBUG: Found 9854 points in 3.68737602234s
2019-04-24 13:15:49,865 DEBUG: Found 9903 points in 3.61924815178s
2019-04-24 13:15:50,073 DEBUG: Found 10200 points in 4.36885094643s
2019-04-24 13:15:50,459 DEBUG: Found 9767 points in 3.91109490395s
2019-04-24 13:15:50,470 DEBUG: Found 9794 points in 3.65349507332s
2019-04-24 13:15:50,657 DEBUG: Found 9744 points in 3.53420805931s
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm match_features /code/opensfm
2019-04-24 13:15:51,619 INFO: Matching 21 image pairs
2019-04-24 13:15:51,912 INFO: Matching DJI_0036.JPG  -  1 / 7
2019-04-24 13:15:52,091 INFO: Matching DJI_0032.JPG  -  2 / 7
2019-04-24 13:15:52,293 INFO: Matching DJI_0024.JPG  -  3 / 7
2019-04-24 13:15:52,502 INFO: Matching DJI_0020.JPG  -  4 / 7
2019-04-24 13:15:52,739 INFO: Matching DJI_0016.JPG  -  5 / 7
2019-04-24 13:15:53,001 INFO: Matching DJI_0028.JPG  -  6 / 7
2019-04-24 13:15:53,291 INFO: Matching DJI_0012.JPG  -  7 / 7
2019-04-24 13:15:54,030 DEBUG: DJI_0032.JPG - DJI_0036.JPG has 1630 candidate matches
2019-04-24 13:15:54,031 DEBUG: Robust matching time : 0.000673055648804s
2019-04-24 13:15:54,031 DEBUG: Full matching 1552 / 1630, time: 1.93960094452s
2019-04-24 13:15:54,403 DEBUG: DJI_0024.JPG - DJI_0036.JPG has 23 candidate matches
2019-04-24 13:15:54,725 DEBUG: DJI_0020.JPG - DJI_0036.JPG has 6 candidate matches
2019-04-24 13:15:55,126 DEBUG: DJI_0028.JPG - DJI_0036.JPG has 48 candidate matches
2019-04-24 13:15:55,127 DEBUG: Robust matching time : 0.000622034072876s
2019-04-24 13:15:55,127 DEBUG: Full matching 37 / 48, time: 2.12534999847s
2019-04-24 13:15:55,154 DEBUG: DJI_0016.JPG - DJI_0020.JPG has 979 candidate matches
2019-04-24 13:15:55,155 DEBUG: Robust matching time : 0.000425100326538s
2019-04-24 13:15:55,155 DEBUG: Full matching 971 / 979, time: 2.41605901718s
2019-04-24 13:15:55,191 DEBUG: DJI_0012.JPG - DJI_0036.JPG has 11 candidate matches
2019-04-24 13:15:56,423 DEBUG: DJI_0024.JPG - DJI_0028.JPG has 1280 candidate matches
2019-04-24 13:15:56,424 DEBUG: Robust matching time : 0.000401973724365s
2019-04-24 13:15:56,424 DEBUG: Full matching 1205 / 1280, time: 2.02039909363s
2019-04-24 13:15:56,546 DEBUG: DJI_0020.JPG - DJI_0032.JPG has 1 candidate matches
2019-04-24 13:15:56,776 DEBUG: DJI_0028.JPG - DJI_0032.JPG has 1453 candidate matches
2019-04-24 13:15:56,776 DEBUG: Robust matching time : 0.000366926193237s
2019-04-24 13:15:56,776 DEBUG: Full matching 1426 / 1453, time: 1.64939117432s
2019-04-24 13:15:57,236 DEBUG: DJI_0012.JPG - DJI_0028.JPG has 9 candidate matches
2019-04-24 13:15:57,283 DEBUG: DJI_0016.JPG - DJI_0036.JPG has 7 candidate matches
2019-04-24 13:15:58,019 DEBUG: DJI_0024.JPG - DJI_0032.JPG has 28 candidate matches
2019-04-24 13:15:58,258 DEBUG: DJI_0020.JPG - DJI_0024.JPG has 1049 candidate matches
2019-04-24 13:15:58,258 DEBUG: Robust matching time : 0.000356912612915s
2019-04-24 13:15:58,258 DEBUG: Full matching 1034 / 1049, time: 1.71252894402s
2019-04-24 13:15:58,775 DEBUG: DJI_0012.JPG - DJI_0024.JPG has 16 candidate matches
2019-04-24 13:15:58,819 DEBUG: DJI_0016.JPG - DJI_0032.JPG has 13 candidate matches
2019-04-24 13:15:59,740 DEBUG: DJI_0020.JPG - DJI_0028.JPG has 10 candidate matches
2019-04-24 13:16:00,155 DEBUG: DJI_0012.JPG - DJI_0032.JPG has 13 candidate matches
2019-04-24 13:16:00,262 DEBUG: DJI_0016.JPG - DJI_0028.JPG has 12 candidate matches
2019-04-24 13:16:01,543 DEBUG: DJI_0012.JPG - DJI_0020.JPG has 19 candidate matches
2019-04-24 13:16:01,666 DEBUG: DJI_0016.JPG - DJI_0024.JPG has 18 candidate matches
2019-04-24 13:16:02,786 DEBUG: DJI_0012.JPG - DJI_0016.JPG has 1349 candidate matches
2019-04-24 13:16:02,787 DEBUG: Robust matching time : 0.000494956970215s
2019-04-24 13:16:02,787 DEBUG: Full matching 1334 / 1349, time: 1.24396491051s
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm create_tracks /code/opensfm
2019-04-24 13:16:03,137 INFO: reading features
2019-04-24 13:16:03,346 DEBUG: Merging features onto tracks
2019-04-24 13:16:03,398 DEBUG: Good tracks: 7507
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm reconstruct /code/opensfm
2019-04-24 13:16:03,837 INFO: Starting incremental reconstruction
2019-04-24 13:16:05,055 INFO: Starting reconstruction with DJI_0032.JPG and DJI_0036.JPG
2019-04-24 13:16:05,123 INFO: Two-view reconstruction inliers: 1557 / 1562
2019-04-24 13:16:05,193 INFO: Triangulated: 1557
2019-04-24 13:16:05,239 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 1.775098e+01, Final cost: 1.749867e+01, Termination: CONVERGENCE
2019-04-24 13:16:05,311 DEBUG: Ceres Solver Report: Iterations: 1, Initial cost: 1.756512e+01, Final cost: 1.749631e+01, Termination: CONVERGENCE
2019-04-24 13:16:05,558 DEBUG: Ceres Solver Report: Iterations: 50, Initial cost: 3.091005e+01, Final cost: 3.043967e+01, Termination: NO_CONVERGENCE
2019-04-24 13:16:05,559 INFO: Removed outliers: 0
2019-04-24 13:16:05,560 INFO: -------------------------------------------------------
2019-04-24 13:16:05,562 INFO: DJI_0028.JPG resection inliers: 16 / 23
2019-04-24 13:16:05,569 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 3.536706e+02, Final cost: 3.530897e+02, Termination: CONVERGENCE
2019-04-24 13:16:05,570 INFO: Adding DJI_0028.JPG to the reconstruction
2019-04-24 13:16:05,649 INFO: Re-triangulating
2019-04-24 13:16:06,061 DEBUG: Ceres Solver Report: Iterations: 50, Initial cost: 4.875457e+02, Final cost: 2.348240e+02, Termination: NO_CONVERGENCE
2019-04-24 13:16:06,222 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 2.350220e+02, Final cost: 2.348207e+02, Termination: CONVERGENCE
2019-04-24 13:16:06,223 INFO: Removed outliers: 6
2019-04-24 13:16:06,249 INFO: -------------------------------------------------------
2019-04-24 13:16:06,252 INFO: Some images can not be added
2019-04-24 13:16:06,252 INFO: -------------------------------------------------------
2019-04-24 13:16:06,402 DEBUG: Ceres Solver Report: Iterations: 7, Initial cost: 8.177270e+00, Final cost: 6.776466e+00, Termination: CONVERGENCE
2019-04-24 13:16:06,403 INFO: Removed outliers: 0
2019-04-24 13:16:06,547 INFO: Starting reconstruction with DJI_0012.JPG and DJI_0016.JPG
2019-04-24 13:16:06,602 INFO: Two-view reconstruction inliers: 1334 / 1334
2019-04-24 13:16:06,660 INFO: Triangulated: 1334
2019-04-24 13:16:06,707 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 1.401281e+01, Final cost: 1.370075e+01, Termination: CONVERGENCE
2019-04-24 13:16:06,795 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 1.377359e+01, Final cost: 1.367603e+01, Termination: CONVERGENCE
2019-04-24 13:16:07,025 DEBUG: Ceres Solver Report: Iterations: 50, Initial cost: 3.053236e+01, Final cost: 2.935550e+01, Termination: NO_CONVERGENCE
2019-04-24 13:16:07,026 INFO: Removed outliers: 0
2019-04-24 13:16:07,026 INFO: -------------------------------------------------------
2019-04-24 13:16:07,035 INFO: DJI_0020.JPG resection inliers: 11 / 11
2019-04-24 13:16:07,118 DEBUG: Ceres Solver Report: Iterations: 7, Initial cost: 9.528660e+00, Final cost: 9.209845e+00, Termination: CONVERGENCE
2019-04-24 13:16:07,118 INFO: Adding DJI_0020.JPG to the reconstruction
2019-04-24 13:16:07,163 INFO: Re-triangulating
2019-04-24 13:16:07,518 DEBUG: Ceres Solver Report: Iterations: 50, Initial cost: 1.317476e+02, Final cost: 3.921036e+01, Termination: NO_CONVERGENCE
2019-04-24 13:16:07,947 DEBUG: Ceres Solver Report: Iterations: 50, Initial cost: 3.978673e+01, Final cost: 3.877263e+01, Termination: NO_CONVERGENCE
2019-04-24 13:16:07,947 INFO: Removed outliers: 0
2019-04-24 13:16:07,962 INFO: -------------------------------------------------------
2019-04-24 13:16:07,963 INFO: DJI_0024.JPG resection inliers: 6 / 6
2019-04-24 13:16:07,963 INFO: Some images can not be added
2019-04-24 13:16:07,963 INFO: -------------------------------------------------------
2019-04-24 13:16:08,100 DEBUG: Ceres Solver Report: Iterations: 4, Initial cost: 4.748491e+00, Final cost: 4.745082e+00, Termination: CONVERGENCE
2019-04-24 13:16:08,100 INFO: Removed outliers: 0
2019-04-24 13:16:08,342 INFO: Reconstruction 0: 3 images, 2959 points
2019-04-24 13:16:08,343 INFO: Reconstruction 1: 3 images, 2294 points
2019-04-24 13:16:08,343 INFO: 2 partial reconstructions in total.
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_visualsfm --image_extension png --scale_focal 1 /code/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm undistort --image_format png --image_scale 1 /code/opensfm
2019-04-24 13:16:09,142 DEBUG: Undistorting the reconstruction
2019-04-24 13:16:09,553 DEBUG: Undistorting image DJI_0036.JPG
2019-04-24 13:16:09,737 DEBUG: Undistorting image DJI_0036.JPG
2019-04-24 13:16:09,933 DEBUG: Undistorting image DJI_0036.JPG
2019-04-24 13:16:10,137 DEBUG: Undistorting image DJI_0028.JPG
2019-04-24 13:16:10,337 DEBUG: Undistorting image DJI_0028.JPG
2019-04-24 13:16:10,551 DEBUG: Undistorting image DJI_0028.JPG
2019-04-24 13:16:10,747 DEBUG: Undistorting image DJI_0032.JPG
2019-04-24 13:16:10,982 DEBUG: Undistorting image DJI_0032.JPG
2019-04-24 13:16:10,982 DEBUG: Undistorting image DJI_0032.JPG
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /code/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_geocoords /code/opensfm --transformation --proj '+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=17 '
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running SMVS Cell
[DEBUG]   running /code/SuperBuild/src/elibs/mve/apps/makescene/makescene /code/opensfm/mve /code/smvs
MVE Makescene (built on Nov 29 2018, 13:57:24)
Info: Detected Noah bundler format.
Reading Bundler file (7 cameras, 2959 features)...
Recognized 7 original images from Noah's Bundler.
Creating output directories...
Saving bundle file...
Writing bundle (7 cameras, 2959 features): /code/smvs/synth_0.out...
Processing view view_0000.mve...
Processing view view_0001.mve...
Processing view view_0002.mve...
  Skipping view_0002.mve: Invalid camera.
Processing view view_0003.mve...
  Skipping view_0003.mve: Invalid camera.
Processing view view_0004.mve...
Processing view view_0005.mve...
  Skipping view_0005.mve: Invalid camera.
Processing view view_0006.mve...
  Skipping view_0006.mve: Invalid camera.

Created 7 views with 3 valid cameras.
Imported 3 undistorted images.
[DEBUG]   running /code/SuperBuild/src/elibs/smvs/app/smvsrecon -t8 -a1.0 --max-pixels=409600 -o1 --debug-lvl=0    /code/smvs
Shading-aware Multi-view Stereo (built on Nov 29 2018, 14:22:31)

Initializing scene with 3 views...
Initialized 3 views (max ID is 4), took 0ms.
Reading Photosynther file (7 cameras, 2959 features)...
Automatic input scale: 3
Input embedding: undist-L3
Output embedding: smvs-B3
Running view selection for 3 views...  done, took 0.009s.
Skipping 3 views with insufficient number of neighbors.
Skipped IDs: 0 1 4 
All valid views are already reconstructed.
Generating Pointcloud, Cutting surfaces for 3 views ...
Done. Took: 0s
Writing PLY file (0 verts, with colors, with normals, with confidences, with values, 0 faces)... done.
[INFO]    Running ODM SMVS Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM Mesh file in: /code/odm_meshing/odm_mesh.ply
[DEBUG]   running /code/SuperBuild/src/PoissonRecon/Bin/Linux/PoissonRecon --in /code/smvs/smvs_dense_point_cloud.ply --out /code/odm_meshing/odm_mesh.dirty.ply --depth 9 --pointWeight 4 --samplesPerNode 1.0 --threads 8 --linearFit 
[DEBUG]   running /code/build/bin/odm_cleanmesh -inputFile /code/odm_meshing/odm_mesh.dirty.ply -outputFile /code/odm_meshing/odm_mesh.ply -removeIslands -decimateMesh 100000  
ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/IO/PLY/vtkPLYWriter.cxx, line 114
vtkPLYWriter (0x172ed30): No data to write!

[DEBUG]   Writing ODM 2.5D Mesh file in: /code/odm_meshing/odm_25dmesh.ply
[WARNING] Cannot calculate GSD, using requested resolution of 5.0
[DEBUG]   ODM 2.5D DSM resolution: 0.2
[INFO]    Created temporary directory: /code/odm_meshing/tmp
[INFO]    Creating DSM for 2.5D mesh
[INFO]    Creating odm_meshing/tmp/mesh_dsm_r0.282842712475 [max] from 1 files
[DEBUG]   running pdal pipeline -i /tmp/tmprquylS.json > /dev/null 2>&1
Traceback (most recent call last):
  File "/code/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/odm_meshing.py", line 108, in process
    method='poisson' if args.fast_orthophoto else 'gridded')
  File "/code/opendm/mesh.py", line 35, in create_25dmesh
    max_workers=max_workers
  File "/code/opendm/dem/commands.py", line 38, in create_dems
    fouts = list(e.map(create_dem_for_radius, radius))
  File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 794, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
    yield future.result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
    raise self._exception
Exception: Child returned 1
+++++++++++++++++++++++++++++++++++++++

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Commandline:
docker run -it --rm -v "$(pwd)/images:/code/images" -v "$(pwd)/odm_orthophoto:/code/odm_orthophoto" -v "$(pwd)/odm_georeferencing:/code/odm_georeferencing" opendronemap/opendronemap

Google Drive Link to images:
https://drive.google.com/open?id=1zErT69iOn77QtWMfMTXjyYwLtJt1qWyp

**Comment by pierotofy** [comment]
Just ran this dataset with the latest ODM (plus `--crop 0` to avoid an issue with cropping) and got a result back:

![image](https://user-images.githubusercontent.com/1951843/92954935-50d68680-f432-11ea-99f8-97ec55e981f2.png)

You'll need more images to get a better looking reconstruction. :+1: 

I'll close this for now.
