### ISSUE TITLE
dem2mesh sometimes fails with "Unable to reduce mesh"

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#996]
Running /code/SuperBuild/src/dem2mesh/dem2mesh -inputFile /var/www/data/f8f86587-d2da-44c9-b697-8bf9eb1784e5/odm_meshing/tmp/mesh_dsm.tif -outputFile /var/www/data/f8f86587-d2da-44c9-b697-8bf9eb1784e5/odm_meshing/odm_25dmesh.dirty.ply -maxVertexCount 100000
Unable to reduce mesh.
Traceback (most recent call last):
File "/code/run.py", line 56, in <module>
app.execute()
File "/code/stages/odm_app.py", line 94, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 375, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 356, in run
self.process(self.args, outputs)
File "/code/stages/odm_meshing.py", line 71, in process
method='poisson' if args.fast_orthophoto else 'gridded')
File "/code/opendm/mesh.py", line 38, in create_25dmesh
mesh = dem_to_mesh_gridded(os.path.join(tmp_directory, 'mesh_dsm.tif'), outMesh, maxVertexCount, verbose)
File "/code/opendm/mesh.py", line 100, in dem_to_mesh_gridded
' {verbose} '.format(**kwargs))
File "/code/opendm/system.py", line 76, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1

Test case unavailable.

**Comment by pierotofy** [comment]
This should be fixed by https://github.com/OpenDroneMap/dem2mesh/commit/965d8b51a8b50d4cb1216bbe255121a86039896b
